"""Verify local mTSBench files against a fixed-revision official relay manifest."""

from __future__ import annotations

import argparse
from pathlib import Path

from common import MTSBENCH_REVISION_MANIFEST_PATH, verify_mtsbench_revision_manifest


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--official-manifest",
        type=Path,
        default=MTSBENCH_REVISION_MANIFEST_PATH,
        help="CSV artifact generated by the fixed-revision GitHub Actions relay",
    )
    args = parser.parse_args()
    verification = verify_mtsbench_revision_manifest(args.official_manifest)
    print(f"verified {(verification['status'] == 'match').sum()}/{len(verification)} fixed-revision mTSBench files")


if __name__ == "__main__":
    main()
